### PR TITLE
Fix on os x, reduce  blinking.

### PR DESCRIPTION
**Pull request by Tritlo**

### CODE REVIEW

**Comment by ayyess** [comment]
That's a good catch that `rm` asks for confirmation on osx. What is the benefit of deleting and then touching the temp file rather than the oneliner?
I guess whether to show the prompt in one go or as it's elements load is personal preference. I'd like to wait on the discussion at https://github.com/bhilburn/powerlevel9k/pull/262

**Comment by Tritlo** [comment]
The one liner does not work on OS X, it complains that the file already exists.

The latter could maybe be configureable?

**Comment by ayyess** [comment]
do you have `setopt noclobber` set somewhere? `>!` could be used to force clobber. 
Yes definitely.

**Comment by Tritlo** [comment]
No, don't think so. I think this approach is better, as rm and touch works everywhere.

**Comment by Tritlo** [comment]
Alright, if `POWERLEVEL9K_RPROMPT_RENDER_ASAP` is `true`, it renders on each part, otherwise when they are all finished.

**Comment by Tritlo** [comment]
I might have `noclobber` set somewhere, but I did not do so myself. This leads me to believe that `noclobber` is the default in OS X, so I think we should rather go with the approach that works by default (instead of asking users to change the defaults).

**Comment by Tritlo** [comment]
alright, it now uses the force clobber.

**Comment by ayyess** [comment]
Alright nice. The `POWERLEVEL9K_RPROMPT_RENDER_ASAP` is a good idea.  I'll merge your changes and that should change my pull request to bhilburn.

**Comment by Tritlo** [comment]
Thanks! Also, great idea btw! I had disabled most segments on my setup due to the slowness, but this makes it all much nicer.

**Comment by ayyess** [comment]
Ha I usually just use the status and vcs element. I enabled all of them and even added a sleep in the loop to check they were loading asynchronously.

**Pull request merged**
