### PR TITLE
Clean up next branch

### PR DESCRIPTION
**Pull request by Tritlo**
I squashed together my commits and added yours to the next branch, so that it is cleaner (and thus more acceptable).

### CODE REVIEW

**Comment by Tritlo** [comment]
I think you should accept this pull request, then make a pull request from this next branch to bhilburns next branch, and close the previous one.

**Comment by Tritlo** [comment]
Could you maybe remove the comments and then squash together your commits? Then I would say it was pretty ready for merging right away. You can then force push to the branch to update it (and thus the pull request).

**Comment by ayyess** [comment]
I don't rebase often so I hope those commits look ok.

**Comment by Tritlo** [comment]
Looks great!

**Comment by ayyess** [comment]
Just a heads up, I added a change to make sure the async process was killed during `tidy` on [line 1035](https://github.com/bhilburn/powerlevel9k/pull/263/files#diff-ea5a405f0331722fc10a832209ffe20bR1035).

**Comment by Tritlo** [comment]
I get now: `tidy:unset:6: not enough arguments`

**Comment by ayyess** [comment]
I was copying your usage of `unset` e.g. `unset $var`. Is variable expansion meant to be used here as if `var` is not defined, `unset $var` will expand to just `unset`? I think that could be the reason and have removed the dollar from my commit.

**Comment by Tritlo** [comment]
Could you join me on gitter?

**Pull request merged**
